### PR TITLE
feature: diffing between different releases

### LINKED ISSUE #130: Allow diffing between 2 different releases
We have several charts that we install a dozen of them.  IT would be highly useful if we could diff between 2 different releases.

### PR DESCRIPTION
**Pull request by aananthraj**
Hi,

This PR resolves #130 and it contains the following changes
 - add diff release subcommand to compare different releases
 - update subcommand usage in README.md 
 - adds go report card badge and license badge to the README.md 

suggestions and comments..?

### CODE REVIEW

**Comment by sstarcher** [comment]
Looking greatly improved.  I tested it against 2 releases I have that are very complicated.
`customer1-qc`
`customer2-qc`

It looks to be working normally except for one instance.  I have a single file in my helm chart called networkpolicy.yaml.  This single file always contains 2 yaml docs that are 2 NetworkPolicy docs.  They both should differ and show up in the diff, but I see the first doc being diffed with the second customers doc.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "apps.fullname" . }}-cluster
  labels:
    {{- include "labels" . | indent 4 }}
spec:
  podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "apps.fullname" . }}-all
  labels:
{{ include "labels" . | indent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
```

Diff

```
app/templates/network-policy.yaml has changed:
  # Source: app/templates/network-policy.yaml
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
-   name: customer1-qc-app-cluster
-   labels:
+   name: customer2-qc-app-all
+   labels:
+
      app: app
      heritage: Tiller
-     release: customer1-qc
+     release: customer2-qc
      environment: qc
-     customer: customer1
+     customer: customer2
  spec:
    podSelector: {}
    policyTypes:
    - Egress
```

I should be seeing 2 network policy diffs

where customer1-cluster is being diffed against customer2-cluster, but instead I see a single one for customer1-cluster being diffed against customer2-all.

**Comment by sstarcher** [comment]
I did a few more diffs and so for everything else except for that issue with 2 yaml docs in a single helm chart file looks good.

**Comment by aananthraj** [comment]
I guess helm templates are rendered and  applied as a whole and kubernetes takes care of creating multiple objects from same yaml file.
Will check further about this.
Have you ever did  a `helm diff upgrade` with the file you have mentioned above, does it show as two individual network policy files..?

**Comment by sstarcher** [comment]
It shows them both at 2 separate parts in the diff output they are not together and are separated by multiple other diffs.
`customer, customer-apps-all, NetworkPolicy (networking.k8s.io) has changed:`
`customer, customer-cluster, NetworkPolicy (networking.k8s.io) has changed:`

**Comment by aananthraj** [comment]
@sstarcher resolved the above mentioned issue. now we get the diff for object files separately.
do let me know for further enhancements or changes required.

**Comment by sstarcher** [comment]
LGTM, the issue is fixed and I am not seeing anything that's having a issue.

**Comment by aananthraj** [comment]
Thanks @sstarcher ,  for the prompt feedback :+1:

now comes the bigger task :laughing: 
Getting it reviewed and merged .

**Comment by aananthraj** [comment]
`diff release` on completely independent releases  (two different charts) would be meaningless.
hence we need to impose restriction based on chart names. i.e only releases installed using the same chart will be shown diff. 

```
$ helm diff release app-1 foo
Error : Incomparable Releases 
 Unable to compare releases from two different charts "demo" "ibm-nginx-dev". 
 try helm diff release --help to know more
```
can this be added..?

**Comment by sstarcher** [comment]
@aananthraj I have one consideration for that are you blocking it just on the chart name or the repo/chart name?  Just to confirm it's only the chart name correct?  I have a usecase for having a beta/chart and a stable/chart.

**Comment by sstarcher** [comment]
@databus23 Could we get a look and get this merged and released pretty please.

**Comment by aananthraj** [comment]
> Just to confirm it's only the chart name correct?

Yes @sstarcher,  just based on chart names.

**Comment by aananthraj** [comment]
@databus23 , @mumoshu any update on this..?

**Pull request merged**
