### PR TITLE
add env var HELM_DIFF_NORMALIZE_MANIFESTS=true for flag --normalize-m…

### PR DESCRIPTION
**Pull request by Anthon129**
…anifests

### CODE REVIEW

**Comment by Anthon129** [comment]
Hi

I have a scenario using helmfile apply where the golang code behind the scenes runs helm diff upgrade followed by helm upgrade --install. I need to add the flag --normalize-manifests (to helm diff command) due to other reasons but this flag is unknown to helm upgrade (causing it to fail) and I am not able to apply separate individual flags to each of the commands. The flags applied to helm diff upgrade will be applied to helm upgrade.

Can we add an environment variable (i.e. HELM_DIFF_NORMALIZE_MANIFESTS=true) that would have the same effect as --normalize-manifests ?

Thanks

**Review by oik741 — APPROVED** [review]
LGTM

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks for your contribution @Anthon129!

**Comment by dudicoco** [comment]
Hi @databus23 and @mumoshu.

Can we please merge this?

**Comment by drcrees** [comment]
👋 Hi @databus23 and @mumoshu,

Just checking in... this would greatly help clean up diffs we are generating through Helmfile.

**Comment by frank-berlin** [comment]
+1

**Comment by drcrees** [comment]
Thank you! 🙏

**Pull request merged**
