### PR TITLE
change path of install script

### PR DESCRIPTION
**Pull request by bakito**
This PR sets the path of the install and update script. 

Without this dir change the helm plugin install failed with helm3.

Regards,
bakito

### CODE REVIEW

**Comment by databus23** [comment]
Thanks for the PR. Bug can you provide the actual failure that is happening to you. Because for me the install script works.
On which platform are you trying to install this plugin? Would you be so kind to provide more details about the issue so I can try to understand the root cause better.
The install script is a tricky beast and has bitten us quite a few times so I'm careful to change it.

**Comment by bakito** [comment]
Hi 

I'm installing on ubuntu WSL on windows 10 with helm 3 beta5

I get the following output
```

helm plugin install https://github.com/databus23/helm-diff
Downloading https://github.com/databus23/helm-diff/releases/download/v2.11.0%2B5/helm-diff-linux.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   609    0   609    0     0   1162      0 --:--:-- --:--:-- --:--:--  1162
100 6953k  100 6953k    0     0   422k      0  0:00:16  0:00:16 --:--:--  570k
Preparing to install into The Kubernetes package manager

Common actions for Helm:

- helm search:    search for charts
- helm fetch:     download a chart to your local directory to view
- helm install:   upload the chart to Kubernetes
- helm list:      list releases of charts

Environment:
  $XDG_CACHE_HOME     set an alternative location for storing cached files.
  $XDG_CONFIG_HOME    set an alternative location for storing Helm configuration.
  $XDG_DATA_HOME      set an alternative location for storing Helm data.
  $HELM_DRIVER        set the backend storage driver. Values are: configmap, secret, memory
  $HELM_NO_PLUGINS    disable plugins. Set HELM_NO_PLUGINS=1 to disable plugins.
  $KUBECONFIG         set an alternative Kubernetes configuration file (default "~/.kube/config")

Helm stores configuration based on the XDG base directory specification, so

- cached files are stored in $XDG_CACHE_HOME/helm
- configuration is stored in $XDG_CONFIG_HOME/helm
- data is stored in $XDG_DATA_HOME/helm

By default, the default directories depend on the Operating System. The defaults are listed below:

+------------------+---------------------------+--------------------------------+-------------------------+
| Operating System | Cache Path                | Configuration Path             | Data Path               |
+------------------+---------------------------+--------------------------------+-------------------------+
| Linux            | $HOME/.cache/helm         | $HOME/.config/helm             | $HOME/.local/share/helm |
| macOS            | $HOME/Library/Caches/helm | $HOME/Library/Preferences/helm | $HOME/Library/helm      |
| Windows          | %TEMP%\helm               | %APPDATA%\helm                 | %APPDATA%\helm          |
+------------------+---------------------------+--------------------------------+-------------------------+

Usage:
  helm [command]

Available Commands:
  2to3        migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
  completion  Generate autocompletions script for the specified shell (bash or zsh)
  create      create a new chart with the given name
  dependency  manage a chart's dependencies
  diff        Preview helm upgrade changes as a diff
  env         Helm client environment information
  get         download extended information of a named release
  help        Help about any command
  history     fetch release history
  install     install a chart
  lint        examines a chart for possible issues
  list        list releases
  package     package a chart directory into a chart archive
  plugin      add, list, or remove Helm plugins
  pull        download a chart from a repository and (optionally) unpack it in local directory
  repo        add, list, remove, update, and index chart repositories
  rollback    roll back a release to a previous revision
  search      search for a keyword in charts
  show        show information of a chart
  status      displays the status of the named release
  template    locally render templates
  test        run tests for a release
  uninstall   uninstall a release
  upgrade     upgrade a release
  verify      verify that a chart at the given path has been signed and is valid
  version     print the client version information

Flags:
      --add-dir-header                   If true, adds the file directory to the header
      --alsologtostderr                  log to standard error as well as files
      --debug                            enable verbose output
  -h, --help                             help for helm
      --kube-context string              name of the kubeconfig context to use
      --kubeconfig string                path to the kubeconfig file
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   If non-empty, write log files in this directory
      --log-file string                  If non-empty, use this log file
      --log-file-max-size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
  -n, --namespace string                 namespace scope for this request (default "six-project-spaces")
      --registry-config string           path to the registry config file (default "/home/tkb16/.config/helm/registry.json")
      --repository-cache string          path to the file containing cached repository indexes (default "/home/tkb16/.cache/helm/repository")
      --repository-config string         path to the file containing repository names and URLs (default "/home/tkb16/.config/helm/repositories.yaml")
      --skip-headers                     If true, avoid header prefixes in the log messages
      --skip-log-headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Use "helm [command] --help" for more information about a command./plugins/helm-diff
mkdir: cannot create directory ‘The Kubernetes package manager\n\nCommon actions for Helm:\n\n- helm search:    search for charts\n- helm fetch:     download a chart to your local directory to view\n- helm install:   upload the chart to Kubernetes\n- helm list:      list releases of charts\n\nEnvironment:\n  $XDG_CACHE_HOME     set an alternative location for storing cached files.\n  $XDG_CONFIG_HOME    set an alternative location for storing Helm configuration.\n  $XDG_DATA_HOME      set an alternative location for storing Helm data.\n  $HELM_DRIVER        set the backend storage driver. Values are: configmap, secret, memory\n  $HELM_NO_PLUGINS    disable plugins. Set HELM_NO_PLUGINS=1 to disable plugins.\n  $KUBECONFIG         set an alternative Kubernetes configuration file (default "~’: File name too long
Failed to install helm-diff
\tFor support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
```

**Comment by databus23** [comment]
Ok from the output I gather you are trying to install v2.11.0+5 of this plugin with helm v3.0.0-beta.5. This is will not work.
Can you trying installing the plugin using ` helm plugin install https://github.com/databus23/helm-diff --version v3.0.0-rc.5`?

**Comment by bakito** [comment]
it works with helm plugin install https://github.com/databus23/helm-diff --version v3.0.0-rc.5

Do you have any idey why installing with no version installs 2.11?

**Comment by databus23** [comment]
Because our 3.0.0-rc releases of this plugin are pre-release. The install script fetches whatever is returned by` https://api.github.com/repos/databus23/helm-diff/releases/latest` which would be this according to GitHub:
image

**Comment by bakito** [comment]
ok
In that case I close the PR, thx for the support

**Pull request closed without merging**
