### PR TITLE
First pass adding option to disable test hooks specifically

### PR DESCRIPTION
**Pull request by regner**
This is for #114

### CODE REVIEW

**Comment by databus23** [comment]
@mumoshu looks like this broke the tests, no?

**Comment by regner** [comment]
Dang! I thought I ran tests but I may not have after I made the final changes. I will take a look today.

Is there a reason tests don't get run on every commit?

**Comment by regner** [comment]
@databus23 the tests all pass for me. May I ask which tests are failing for you?

I just ran `go test -v ./...` in the root of the repo.

**Comment by databus23** [comment]
https://circleci.com/gh/databus23/helm-diff/22

**Comment by regner** [comment]
Yeah, those tests are failing and clearly should be based on the change. I don't understand why they do not fail for me... thats so add. Fixing this now.

**Comment by regner** [comment]
I have opened a PR that should fix the tests.

**Pull request merged**
