### PR TITLE
Download remote chart to Archive dir

### PR DESCRIPTION
**Pull request by aananthraj**
Downloading remote chart to Archive dir (~/.helm/cache/archive) would keep the current dir clean.

### CODE REVIEW

**Comment by elemental-lf** [comment]
Sounds like a good idea to prevent clutter. Could there be any issues when running multiple helm instances in parallel? I haven't looked into DownloadTo to see if it does any locking or so.

**Comment by aananthraj** [comment]
I just made it to mimics the way, Helm works. It works fine to me (as am using them often)
BTW what do you mean by running multiple helm instances in parallel? could you be brief?

**Comment by elemental-lf** [comment]
@aananthraj I mean multiple instances of helm running under the same user account at the same time and so using the same archive directory. I haven't looked into the Helm source code if it does anything to prevent races between different processes when both try to download the same chart to the archive directory at the same time and so possibly corrupting the file or leading to failed verifications of the chart. If locking is done in downloadTo we'd be fine. If this isn't the case then we'd need to mimic the locking logic in helm diff, too, when writing to the shared archive directory.

**Comment by aananthraj** [comment]
@elemental-lf , That was nice. Thanks..!!.

I have a query.
> when both try to download the same chart to the archive directory at the same time and so possibly corrupting the file or leading to failed verifications of the chart.

This could happen in PWD as well right..?, I mean when charts are downloaded to current working directory.

upon inspection codes of helm and helm diff plugin, I would like to share the following infrences.

helm diff plugin uses `DownloadTo` func from Helm's official `k8s.io/helm/pkg/downloader` package. 
>  If this isn't the case then we'd need to mimic the locking logic in helm diff, too, when writing to the shared archive directory

so logic is exactly the same.

**Comment by elemental-lf** [comment]
This would also happen with the download to the cwd. But if there is a locking problem (at all), then it would be confined. I took a quick look at Helm now and I don't see any looking, so we're probably fine (or not worse than Helm itself).

**Comment by aananthraj** [comment]
ya, exactly 😄 , can this be merged..? now.

**Comment by databus23** [comment]
Thanks!

**Comment by aananthraj** [comment]
Thanks @databus23  and @elemental-lf .
It would be helpful , If we could work together on PR #22 and #24 as well.

**Pull request merged**
