### PR TITLE
Allow passing the chart repo to helm template

### PR DESCRIPTION
**Pull request by aackerman**

### CODE REVIEW

**Review by mumoshu — APPROVED** [review]
Wow, I've never realized helm had this option and I'm entirely unsure when this is supposed to be used, but I learned that it works like:

```
helm template --repo https://charts.helm.sh/stable envoy
```

Anyway, we'd better have this to make it consistent with `helm template`.

LGTM. Thanks a lot for your contribution @aackerman!

**Comment by aackerman** [comment]
@mumoshu awesome, thanks for getting this merged. This is important for remote repos that aren't already local.

**Comment by mumoshu** [comment]
@aackerman Thanks for the info! So, this just frees you from being required to run `helm repo add` beforehand, right?

**Comment by aackerman** [comment]
@mumoshu yep that's definitely what I'm using it for

**Comment by mumoshu** [comment]
@aackerman Got it. Thanks for clarifying ☺️

**Pull request merged**
