### PR TITLE
fix: added macOS ARM M1 architecture support

### LINKED ISSUE #262: Build for Apple Silicon (macos-arm64)
Plugin install fails on ARM-based Macs. I was able to build from source and copy the executable to my helm plugins directory.

I am using helm 3.5.2 and helmfile 0.138 from Homebrew.

```
nick@macbook-air ~ % helm plugin install https://github.com/databus23/helm-diff
No prebuild binary for macos-arm64.
Failed to install helm-diff
	For support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
```

### PR DESCRIPTION
**Pull request by atassis**
Fixes #262

### CODE REVIEW

**Comment by rafilkmp3** [comment]
bump

**Comment by zzh8829** [comment]
bump @databus23

**Comment by draveness** [comment]
@databus23

**Comment by nauxliu** [comment]
@mumoshu Could you take a look at this PR and help us get this merged. Thanks!

**Review by mumoshu — APPROVED** [review]
I have no M1 macOS in my hand so I'm going to merge this believing you guys have tested this manually.
Thanks for your patience and contribution everyone!

**Pull request merged**
