### PR TITLE
Add post-renderer-args flag

### PR DESCRIPTION
**Pull request by danlenar**
Implements #396

Add post-renderder-args flags to keep in sync with helm's post-renderer-args flag

### CODE REVIEW

**Comment by sherifkayad** [comment]
@databus23 any chance we can get this one merged?

**Comment by alice-sawatzky** [comment]
I'm using `--post-renderer-args` in my workaround implementation for [this Helm bug](https://github.com/helm/helm/pull/11440), so now i'm considering switching to this fork of `helm-diff` as a temporary workaround for `helm-diff`'s lack of support for my temporary workaround for Helm :zany_face:

So, :+1: to this PR as it would make the sentence above less bananas sounding

**Comment by sherifkayad** [comment]
Sorry for nagging again .. but it would be really great to get this one merged 😞

**Review by mumoshu — APPROVED** [review]
LGTM. Sorry for the delayed review and thanks a lot for your patience and contribution!

**Pull request merged**
