### PR TITLE
docs(README): fix typo `upgarde` -> `upgrade`

### PR DESCRIPTION
**Pull request by sgoudham**
Hiya :wave:, finishing off what #421 started :D

### CODE REVIEW

**Comment by yxxhero** [comment]
@mumoshu @databus23 thanks.

**Review by mumoshu — APPROVED** [review]
Thanks for fixing it!

**Review by yxxhero — APPROVED** [review]
LGTM

**Review by yardenshoham — APPROVED** [review]

**Review by nullchilly — APPROVED** [review]

**Review by NamesCode — APPROVED** [review]

**Review by isabelroses — APPROVED** [review]
i cant spell need more people to check

**Review by nullishamy — APPROVED** [review]

**Review by nyxkrage — APPROVED** [review]
Awesome change!

**Review by rubyowo — APPROVED** [review]
I'm dyslexic and they both look the same

**Review by iruzo — APPROVED** [review]

**Review by Stonks3141 — APPROVED** [review]
Nice fix!

**Review by nekowinston — APPROVED** [review]

**Review by backwardspy — APPROVED** [review]

**Review by DakshG07 — APPROVED** [review]

**Comment by DakshG07** [comment]
To optimize this PR for all the nuances of the English language, it may be worth your time to consider the alternative spellings of "upgrade":

upgr**a**d**e** as in sn**a**k**e**
upgr**ai**d as in str**ai**t
upgr**ay**d as in gr**ay** (American)
upgr**é**d as in saut**é**
upgr**ea**d as in st**ea**k
upgr**ey**d as in gr**ey** (European)
upgr**eigh**d as in sl**ei**gh
upgr**a**d as in t**a**per
upgr**ei**d as in v**ei**n
upgr**et**d as in fill**et**
upgr**aigh**d as in str**aigh**t

The short "u" sound can also be spelled alteratively:

**u**pgrade as in pneumono**u**ltramicroscopicsilicovolcanoconiosis
**uh**pgrade as in uh

The "d" sound can also have alternatives:

upgra**d**e as in **d**addy
upgra**dd**e as in da**dd**y

In fact, in words like gran**d**mother, han**d**kerchief (spelled correctly) and han**d**some, many people will often drop the "d" sound in pronunciation. Therefore, we could further simplify to:

upgra(d)e as in han(d)kerchief

The "p" sound in upgrade can also be doubled:

u**p**grade as in **p**uppy
u**pp**grade as in pu**pp**y

It's important to acknowledge these possibilities, as, especially for English newcomers, the language can be a mess of complicated, inconsistent spellings. Therefore, I urge you to consider using these alternate spellings where applicable, in order to reduce the learning curve for your tool.

<details>
<summary>
Here's a full list, then, of all 120 possible spellings of "upgrade" to consider:
</summary>
<li>upgra</li>
<li>upgrad</li>
<li>upgradd</li>
<li>upgrai</li>
<li>upgraid</li>
<li>upgraidd</li>
<li>upgré</li>
<li>upgréd</li>
<li>upgrédd</li>
<li>upgrea</li>
<li>upgread</li>
<li>upgreadd</li>
<li>upgrey</li>
<li>upgreyd</li>
<li>upgreydd</li>
<li>upgreigh</li>
<li>upgreighd</li>
<li>upgreighdd</li>
<li>upgrei</li>
<li>upgreid</li>
<li>upgreidd</li>
<li>upgret</li>
<li>upgretd</li>
<li>upgretdd</li>
<li>upgraigh</li>
<li>upgraighd</li>
<li>upgraighdd</li>
<li>upgrae</li>
<li>upgrade</li>
<li>upgradde</li>
<li>uppgra</li>
<li>uppgrad</li>
<li>uppgradd</li>
<li>uppgrai</li>
<li>uppgraid</li>
<li>uppgraidd</li>
<li>uppgré</li>
<li>uppgréd</li>
<li>uppgrédd</li>
<li>uppgrea</li>
<li>uppgread</li>
<li>uppgreadd</li>
<li>uppgrey</li>
<li>uppgreyd</li>
<li>uppgreydd</li>
<li>uppgreigh</li>
<li>uppgreighd</li>
<li>uppgreighdd</li>
<li>uppgrei</li>
<li>uppgreid</li>
<li>uppgreidd</li>
<li>uppgret</li>
<li>uppgretd</li>
<li>uppgretdd</li>
<li>uppgraigh</li>
<li>uppgraighd</li>
<li>uppgraighdd</li>
<li>uppgrae</li>
<li>uppgrade</li>
<li>uppgradde</li>
<li>uhpgra</li>
<li>uhpgrad</li>
<li>uhpgradd</li>
<li>uhpgrai</li>
<li>uhpgraid</li>
<li>uhpgraidd</li>
<li>uhpgré</li>
<li>uhpgréd</li>
<li>uhpgrédd</li>
<li>uhpgrea</li>
<li>uhpgread</li>
<li>uhpgreadd</li>
<li>uhpgrey</li>
<li>uhpgreyd</li>
<li>uhpgreydd</li>
<li>uhpgreigh</li>
<li>uhpgreighd</li>
<li>uhpgreighdd</li>
<li>uhpgrei</li>
<li>uhpgreid</li>
<li>uhpgreidd</li>
<li>uhpgret</li>
<li>uhpgretd</li>
<li>uhpgretdd</li>
<li>uhpgraigh</li>
<li>uhpgraighd</li>
<li>uhpgraighdd</li>
<li>uhpgrae</li>
<li>uhpgrade</li>
<li>uhpgradde</li>
<li>uhppgra</li>
<li>uhppgrad</li>
<li>uhppgradd</li>
<li>uhppgrai</li>
<li>uhppgraid</li>
<li>uhppgraidd</li>
<li>uhppgré</li>
<li>uhppgréd</li>
<li>uhppgrédd</li>
<li>uhppgrea</li>
<li>uhppgread</li>
<li>uhppgreadd</li>
<li>uhppgrey</li>
<li>uhppgreyd</li>
<li>uhppgreydd</li>
<li>uhppgreigh</li>
<li>uhppgreighd</li>
<li>uhppgreighdd</li>
<li>uhppgrei</li>
<li>uhppgreid</li>
<li>uhppgreidd</li>
<li>uhppgret</li>
<li>uhppgretd</li>
<li>uhppgretdd</li>
<li>uhppgraigh</li>
<li>uhppgraighd</li>
<li>uhppgraighdd</li>
<li>uhppgrae</li>
<li>uhppgrade</li>
<li>uhppgradde</li>
</details>

*/s*

**Pull request merged**
