### PR TITLE
Improve code quality using gofmt and go lint

### PR DESCRIPTION
**Pull request by aananthraj**
This PR,
- Refactors code using `gofmt` and `go lint` to improve code quality. 
- Adds scripts to `gofmt` code and to update required changes
- Adds scripts to `go lint` and `go vet` code
- Adds `lint` stage before `build` to retain code quality
- Adds Godocs Badge to README.md

**preview**:
goes from [Go Report Card](https://goreportcard.com/report/github.com/databus23/helm-diff) to [Go Report Card](https://goreportcard.com/report/github.com/aananthraj/helm-diff)

### CODE REVIEW

**Comment by aananthraj** [comment]
@databus23, @mumoshu. Can this be reviewed and merged?

**Comment by aananthraj** [comment]
self-reviewed and pushed the changes.

**Comment by aananthraj** [comment]
> so that the method name conforms to the convention of being "verb (+ noun)".

I do agree with your point. I had to change it, as it was reported by `gofmt` that 
package name and func name are same.

**Comment by mumoshu** [comment]
@aananthraj Ah good point. Then `Just `diff.Manifests` and `diff.Releases` without `Diff` makes sense to me. Would you mind changing code in that way?

It is a breaking change for anyone using helm-diff as a go library. But it isn't an intended use-case at the moment and I'll keep it until I hear from anyone requesting to bring back the go-level API compatibility. That said, please forgive me if I reverted part of this or altered the lint script to ignore errors on the two method names :)

**Comment by aananthraj** [comment]
> Would you mind changing code in that way?

Sure will make those changes and update here
> It is a breaking change for anyone using helm-diff as a go library. 

https://godoc.org/github.com/databus23/helm-diff
Godocs says helm-diff is presently not being used as a golang package.
So i guess change this will have very minimalistic impact.

**Comment by aananthraj** [comment]
@mumoshu made those requested changes

**Comment by aananthraj** [comment]
Thanks @mumoshu for the prompt responce and support 👍

**Pull request merged**
