### PR TITLE
feature(output): add dyff powered output

### PR DESCRIPTION
**Pull request by cwrau**
Adds option to use dyff as a diff renderer

### CODE REVIEW

**Comment by databus23** [comment]
Sorry for taking so long. This looks good. Can you please rebase and run a `go mod tidy`? Otherwise I'm fine to merge this. Thanks!

**Comment by cwrau** [comment]
Sure thing 😊

**Comment by cwrau** [comment]
Heyho 👋, can I do something to get this rollin'? 😊

**Review by mumoshu — APPROVED** [review]
I finally got some time to review this and this looks AWESOME! Thanks a lot for your patience and contribution @cwrau! ☺️ Merging!

**Pull request merged**
